apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker-service
spec:
  selector:
    matchLabels:
      app: message-broker-service
  replicas: 1
  template:
    metadata:
      labels:
        app: message-broker-service
    spec:
      containers:
        - name: message-broker-service
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
              protocol: TCP
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "message-broker-service"
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"