apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-service
spec:
  selector:
    matchLabels:
      app: tracing-service
  replicas: 1
  template:
    metadata:
      labels:
        app: tracing-service
    spec:
      containers:
        - name: tracing-service
          image: jaegertracing/all-in-one
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"