apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: {{ .Values.port.service }}
      targetPort: {{ .Values.port.container }}