apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  selector:
    app: configuration-service
  ports:
    - protocol: TCP
      port: {{ .Values.port.service }}
      targetPort: {{ .Values.port.container }}