tracingServiceHost: tracing-service
dbHost: 192.168.49.1 # host gateway (you can reach host machine inside minikube by using this IP address)
vaultHost: 192.168.49.1 # host gateway (you can reach host machine inside minikube by using this IP address)
configurationServiceHost: configuration-service

app:
  name: gateway-service
  profile: local
image:
  name: fdobrotv/gateway_service:0.5.3
  pullPolicy: Never
replicaCount: 1
port:
  container: 8080
  service: 8080
