apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: {{ .Values.clientService.port.service }}
      targetPort: {{ .Values.clientService.port.container }}
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  selector:
    app: configuration-service
  ports:
    - protocol: TCP
      port: {{ .Values.configurationService.port.service }}
      targetPort: {{ .Values.configurationService.port.container }}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: {{ .Values.gatewayService.port.service }}
      targetPort: {{ .Values.gatewayService.port.container }}