apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-service
spec:
  selector:
    matchLabels:
      app: zookeeper-service
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: zookeeper-service
    spec:
      containers:
        - name: zookeeper-service
          image: wurstmeister/zookeeper
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP